Update code for directory checking
UST-SEAL-Team-4/Machine-Learning-Finals-Project pull request #2
Opened 2024-05-13 12:21 UTC by LexLorenzo

2024-05-14 00:58 UTC, JoshuaEntrata commented on final_project.ipynb
> +    "testing_label_relative = 'Thesis_Folder\\VALDO_Dataset\\Task2'\n",
use environment variable

2024-05-14 01:00 UTC, JoshuaEntrata commented on final_project.ipynb
>     "source": [
for `device_num`, assign this instead para applicable sa different devices

`device_num = torch.cuda.get_device_name(0)`

2024-05-14 01:02 UTC, JoshuaEntrata reviewed
adfsfasd

2024-05-18 02:33 UTC, 1123Alessandro requested changes
Remove logs

2024-05-18 02:52 UTC, LexLorenzo commented
> Remove logs

Done

2024-05-18 03:01 UTC, 1123Alessandro approved these changes

2024-05-18 03:09 UTC, merged